### ISSUE TITLE
Why should I use kafka?

### ISSUE THREAD

**Issue by tombastianello** [pnpolcher/test-repo#7]
How does kafka compare to other event stores?

**Comment by pnpolcher** [comment]
Labelling outcome: Can you please provide the repository name and issue number?

**Comment by pnpolcher** [comment]
Kafka is similar to other event stores and commit logs in that it allows applications to store streams of events durably and reliably for later processing. Kafka's strengths compared to other systems are its high throughput, low latency, scalability, and replication capabilities.

**Comment by pnpolcher** [comment]
What would I use Kafka for and what are the benefits?
